global:
  resolve_timeout: 0s
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 72h
  receiver: 'NMS'
receivers:
- name: 'NMS'
  email_configs:
  - to: 'alerts@yourdomain.com'
    from: 'NMS <nms@yourdomain.com>'
    smarthost: relay.yourdomain:587
    headers:
    #Subject: '{{ .CommonLabels.alertname }}{{ if eq .Status "firing" }}'
    html: '{{ range .Alerts }}{{ if eq .Status "firing" }}{{ .Annotations.description }}<br>{{ end }}{{ if eq .Status "resolved" }}{{ .Annotations.Summary }}<br>{{ end }}{{ end }}'    
    send_resolved: true  # Set to 'true' to send resolved notifications as well

  webhook_configs:
  - url: "https://mattermost.yourdomain.com/plugins/alertmanager/api/webhook?token=xxxxxxxxxxxxxxxxxxxxxx"
    send_resolved: true
